DivineWindow.Constants.CountType = {
    BUFF_DEBUFF_EXPIRATION_TIME = "BUFF_DEBUFF_EXPIRATION_TIME",
    BUFF_DEBUFF_STACKS = "BUFF_DEBUFF_STACKS",
    COOLDOWN_TIMER = "COOLDOWN_TIMER",
    COOLDOWN_STACKS = "COOLDOWN_STACKS",
    ON_OFF = "ON_OFF",
};
